# Generated by Django 4.2 on 2023-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='payingguest',
            name='price_range',
            field=models.CharField(default='10000 to 20000', max_length=100),
        ),
        migrations.AddField(
            model_name='payingguest',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payingguest',
            name='college',
            field=models.ManyToManyField(to='database.college'),
        ),
    ]
