# Generated by Django 4.2 on 2023-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_category_options_payingguest_price_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingguest',
            name='type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'CoLive')], default='M', max_length=10),
        ),
    ]
