# Generated by Django 4.2 on 2023-04-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_payingguest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingguest',
            name='price_range',
            field=models.CharField(default='10000 to 20000', max_length=50),
        ),
    ]
